title: FPC5719的博客
url: "http://fpc5719.github.io"
baseurl: ""
description: >
  一个即将（也许是已经）退役的OIer的博客。
  主要是OI相关（但是目前好像全都是杂七杂八的东西？）

email: FPC5719@163.com
author: FPC5719
avatar: "https://avatars3.githubusercontent.com/u/42735573?s=400&v=4"

profile: 我太蒻了
profile_links:
  洛谷: "https://www.luogu.com.cn/blog/hello-world/#"
  Github: "https://github.com/FPC5719"

excerpt_separator: <!--more-->

header:
  links:
    关于: /about/
    分类: /category/

plugins:
 - jekyll-paginate
 - jekyll-gist
 - jemoji

plugins: [jekyll-paginate]
paginate: 5
paginate_path: "page:num"

highlighter: rouge
markdown: kramdown

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

kramdown:
  input: GFM
  syntax_highlighter: rouge
  math_engine: mathjax