title: 蛟川书院2017届3班
url: "http://jc201703.github.io"
baseurl: ""
description: >
  蛟川书院2017届3班的网站

email: jc201703@126.com
author: jc201703

profile: 相信自己，未来可期！

excerpt_separator: <!--more-->

header:
  links:
    关于: /about/
    分类: /category/

plugins:
 - jekyll-paginate
 - jekyll-gist
 - jemoji

plugins: [jekyll-paginate]
paginate: 5
paginate_path: "page:num"

highlighter: rouge
markdown: kramdown

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

kramdown:
  input: GFM
  syntax_highlighter: rouge
  math_engine: mathjax